# Generated by Django 3.1 on 2020-09-20 18:16

from django.db import migrations, models
import virtualclass.models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualclass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='key',
            field=models.CharField(default=virtualclass.models.Student.generate_token, editable=False, max_length=255, verbose_name='confirmation key'),
        ),
    ]
