# Generated by Django 3.1 on 2020-09-27 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Students'},
        ),
    ]
