# Generated by Django 3.1 on 2020-10-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualclass', '0002_auto_20200928_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('video_file', models.FileField(upload_to='')),
            ],
        ),
    ]
