# Generated by Django 3.1.3 on 2020-12-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualclass', '0003_auto_20201208_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='balance',
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True),
        ),
    ]
