# Generated by Django 3.1 on 2020-10-14 20:48

from django.db import migrations, models
import django_encrypted_filefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('virtualclass', '0004_auto_20201012_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_valid',
            field=models.BooleanField(default=False, verbose_name='has valid email'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=django_encrypted_filefield.fields.EncryptedFileField(upload_to='videos/'),
        ),
    ]
