# Generated by Django 3.1.3 on 2020-12-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualclass', '0004_student_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=19),
        ),
    ]
