# Generated by Django 3.1 on 2020-10-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualclass', '0005_auto_20201015_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='videos',
            field=models.ManyToManyField(to='virtualclass.Video'),
        ),
    ]
