# Generated by Django 3.1 on 2020-10-14 21:54

from django.db import migrations
import django_encrypted_filefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('virtualclass', '0006_student_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=django_encrypted_filefield.fields.EncryptedFileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
