# Generated by Django 3.1.3 on 2021-06-02 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualclass', '0006_auto_20201217_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.TextField(null=True, unique=True, verbose_name='payment id')),
                ('payment_link', models.TextField(verbose_name='payment link')),
                ('idpay_track_id', models.IntegerField(null=True, unique=True)),
                ('bank_track_id', models.TextField(null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='amount')),
                ('hashed_card_number', models.TextField(default='****', verbose_name='hashed card number')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.IntegerField(choices=[(1, 'Incomplete'), (2, 'Unsuccessful'), (3, 'Error'), (4, 'Blocked'), (5, 'Payerredirect'), (6, 'Systemredirect'), (7, 'Cancelled'), (8, 'Gatewayredirect'), (10, 'Verificationpending'), (100, 'Verified'), (101, 'Alreadyverified'), (200, 'Received')], default=1)),
            ],
        ),
    ]
