# Generated by Django 3.1 on 2020-10-14 21:57

from django.db import migrations
import django_encrypted_filefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('virtualclass', '0007_auto_20201015_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=django_encrypted_filefield.fields.EncryptedFileField(blank=True, upload_to='videos/'),
        ),
    ]
