# Generated by Django 3.1 on 2020-10-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualclass', '0008_auto_20201015_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
