# Generated by Django 3.1.3 on 2021-06-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualclass', '0009_auto_20210602_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card_number',
            field=models.TextField(default='****', verbose_name='card number'),
        ),
    ]
