# Generated by Django 3.1 on 2020-10-15 12:11

from django.db import migrations
import django_encrypted_filefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('virtualclass', '0009_auto_20201015_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=django_encrypted_filefield.fields.EncryptedFileField(upload_to='videos/'),
        ),
    ]
